"""add specialization to user

Revision ID: 96dbb40de4ff
Revises: 183d27f79564
Create Date: 2025-07-26 18:38:58.607826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dbb40de4ff'
down_revision: Union[str, Sequence[str], None] = '183d27f79564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialization')
    # ### end Alembic commands ###
